name: Deploy Static Website

on:
  push:
    branches:
      - main  # Deploy only when the main branch is updated

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop static-website || true
            docker rm static-website || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/static-website:latest
            docker run -d --name static-website -p 80:80 ${{ secrets.DOCKER_USERNAME }}/static-website:latest
